name: 'AWS Marketplace Publish'
description: 'Publish a new version of a product in AWS Marketplace'
author: 'Luca Comellini <lucacome>'
inputs:
  product-id:
    description: 'Product ID'
    required: true
  release-notes:
    description: 'Release notes for the new version'
    required: true
  registry:
    description: 'ECR registry with tag'
    required: true
  version:
    description: 'Version of the new release'
    required: true
  description:
    description: 'Description of the new release'
    required: true
  usage-instructions:
    description: 'Usage instructions for the new release'
    required: true
  compatible-services:
    description: 'Comma-delimited list of compatible services for this to be deployed with'
    required: false
  resources:
    description: |
      Pass in a JSON array to this. Example: 
      resources: |-
        [
          {
            Name: "Terraform Module",
            Url: "https://github.com/managedoss/terraform-aws-superset"
          },
          {
            Name: "Cloudformation Template",
            Url: "https://us-east-1.console.aws.amazon.com/cloudformation/home#/stacks/quickcreate?templateUrl=https://managedoss-shared-web-assets.s3.amazonaws.com/cloudformation.yml"
          }
        ]
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
